/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-lowest": "rgb(var(--surface-container-lowest-rgb) / <alpha-value>)",
        "surface-container-low": "rgb(var(--surface-container-low-rgb) / <alpha-value>)",
        "surface-container": "rgb(var(--surface-container-rgb) / <alpha-value>)",
        "surface-container-high": "rgb(var(--surface-container-high-rgb) / <alpha-value>)",
        "surface-container-highest": "rgb(var(--surface-container-highest-rgb) / <alpha-value>)",
        "surface": "rgb(var(--surface-rgb) / <alpha-value>)",
        "surface-dim": "rgb(var(--surface-dim-rgb) / <alpha-value>)",
        "surface-bright": "rgb(var(--surface-bright-rgb) / <alpha-value>)",
        "on-surface": "rgb(var(--on-surface-rgb) / <alpha-value>)",
        "on-surface-variant": "rgb(var(--on-surface-variant-rgb) / <alpha-value>)",
        "outline": "rgb(var(--outline-rgb) / <alpha-value>)",
        "outline-variant": "rgb(var(--outline-variant-rgb) / <alpha-value>)",
        "primary": "rgb(var(--primary-rgb) / <alpha-value>)",
        "on-primary": "rgb(var(--on-primary-rgb) / <alpha-value>)",
        "primary-container": "rgb(var(--primary-container-rgb) / <alpha-value>)",
        "on-primary-container": "rgb(var(--on-primary-container-rgb) / <alpha-value>)",
        "secondary": "rgb(var(--secondary-rgb) / <alpha-value>)",
        "on-secondary": "rgb(var(--on-secondary-rgb) / <alpha-value>)",
        "secondary-container": "rgb(var(--secondary-container-rgb) / <alpha-value>)",
        "secondary-fixed": "rgb(var(--secondary-fixed-rgb) / <alpha-value>)",
        "secondary-fixed-dim": "rgb(var(--secondary-fixed-dim-rgb) / <alpha-value>)",
        "tertiary": "rgb(var(--tertiary-rgb) / <alpha-value>)",
        "on-tertiary": "rgb(var(--on-tertiary-rgb) / <alpha-value>)",
        "tertiary-container": "rgb(var(--tertiary-container-rgb) / <alpha-value>)",
        "tertiary-fixed": "rgb(var(--tertiary-fixed-rgb) / <alpha-value>)",
        "tertiary-fixed-dim": "rgb(var(--tertiary-fixed-dim-rgb) / <alpha-value>)",
        "error": "rgb(var(--error-rgb) / <alpha-value>)",
        "error-container": "rgb(var(--error-container-rgb) / <alpha-value>)",
        "on-error": "rgb(var(--on-error-rgb) / <alpha-value>)",
        "background": "rgb(var(--bg-rgb) / <alpha-value>)",
        "on-background": "rgb(var(--on-surface-rgb) / <alpha-value>)",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "full": "9999px",
      },
      fontFamily: {
        display: ["Geist", "sans-serif"],
        headline: ["Geist", "sans-serif"],
        body: ["Geist", "sans-serif"],
        label: ["JetBrains Mono", "monospace"],
        code: ["JetBrains Mono", "monospace"],
      },
      spacing: {
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2rem",
        "gutter": "1rem",
        "gutter-desktop": "1.5rem",
      },
      boxShadow: {
        "cyan-glow": "0 0 16px rgba(0, 229, 255, 0.35)",
        "cyan-subtle": "0 0 20px -3px rgba(0, 229, 255, 0.15)",
        "emerald-glow": "0 0 12px -2px rgba(16, 185, 129, 0.2)",
        "amber-glow": "0 0 14px -2px rgba(245, 158, 11, 0.25)",
        "error-glow": "0 0 16px 0 rgba(239, 68, 68, 0.2)",
      },
    },
  },
  plugins: [],
};
