/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-lowest": "#010f1f",
        "surface-container-low": "#0d1c2d",
        "surface-container": "#122131",
        "surface-container-high": "#1c2b3c",
        "surface-container-highest": "#273647",
        "surface": "#051424",
        "surface-dim": "#051424",
        "surface-bright": "#2c3a4c",
        "on-surface": "#d4e4fa",
        "on-surface-variant": "#bac9cc",
        "outline": "#849396",
        "outline-variant": "#3b494c",
        "primary": "#c3f5ff",
        "on-primary": "#00363d",
        "primary-container": "#00e5ff",
        "on-primary-container": "#00626e",
        "secondary": "#c0c1ff",
        "on-secondary": "#1000a9",
        "secondary-container": "#3131c0",
        "secondary-fixed": "#e1e0ff",
        "secondary-fixed-dim": "#c0c1ff",
        "tertiary": "#a8ffd2",
        "on-tertiary": "#003824",
        "tertiary-container": "#5be9ad",
        "tertiary-fixed": "#6ffbbe",
        "tertiary-fixed-dim": "#4edea3",
        "error": "#ffb4ab",
        "error-container": "#93000a",
        "on-error": "#690005",
        "background": "#051424",
        "on-background": "#d4e4fa",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "full": "9999px",
      },
      fontFamily: {
        display: ["Geist", "sans-serif"],
        headline: ["Geist", "sans-serif"],
        body: ["Geist", "sans-serif"],
        label: ["JetBrains Mono", "monospace"],
        code: ["JetBrains Mono", "monospace"],
      },
      spacing: {
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2rem",
        "gutter": "1rem",
        "gutter-desktop": "1.5rem",
      },
      boxShadow: {
        "cyan-glow": "0 0 16px rgba(0, 229, 255, 0.35)",
        "cyan-subtle": "0 0 20px -3px rgba(0, 229, 255, 0.15)",
        "emerald-glow": "0 0 12px -2px rgba(16, 185, 129, 0.2)",
        "amber-glow": "0 0 14px -2px rgba(245, 158, 11, 0.25)",
        "error-glow": "0 0 16px 0 rgba(239, 68, 68, 0.2)",
      },
    },
  },
  plugins: [],
};
