"""Generate professional standard document templates for Sovereign AI Workbench.

Generates:
1. templates/approval_note.docx — Engineering approval note with AI draft banner,
   structured sections for findings, visual observations, SOP guidance, calculations,
   recommendations, and blank human-review gate.
2. templates/report.docx — Formal technical engineering report template.
3. templates/presentation.pptx — Clean corporate slide presentation template.
"""

from pathlib import Path
import docx
from docx.enum.table import WD_TABLE_ALIGNMENT
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml import OxmlElement, parse_xml
from docx.oxml.ns import nsdecls, qn
from docx.shared import Inches, Pt, RGBColor
import pptx
from pptx.util import Inches as PptxInches, Pt as PptxPt


def set_cell_background(cell, fill_hex: str):
    """Set shading color for a table cell."""
    tcPr = cell._tc.get_or_add_tcPr()
    shd = parse_xml(f'<w:shd {nsdecls("w")} w:fill="{fill_hex}"/>')
    tcPr.append(shd)


def make_approval_note_template(output_path: Path):
    """Create approval note template per 02_DESIGN_DOC.md §10.1."""
    doc = docx.Document()

    # Page Margins: 1 inch
    for section in doc.sections:
        section.top_margin = Inches(1)
        section.bottom_margin = Inches(1)
        section.left_margin = Inches(1)
        section.right_margin = Inches(1)

    # 1. AI-Assisted Draft Banner (Highlighted box)
    banner_table = doc.add_table(rows=1, cols=1)
    banner_table.alignment = WD_TABLE_ALIGNMENT.CENTER
    cell = banner_table.cell(0, 0)
    set_cell_background(cell, "FFF3CD")  # Warning amber-light background
    p = cell.paragraphs[0]
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = p.add_run("⚠️  AI-ASSISTED DRAFT — HUMAN REVIEW & APPROVAL MANDATORY  ⚠️\n")
    run.font.bold = True
    run.font.size = Pt(11)
    run.font.color.rgb = RGBColor(133, 100, 4)

    run_sub = p.add_run(
        "Confidential Internal Industrial Document. Generated by Sovereign AI Workbench.\n"
        "Not certified for final safety-critical engineering, structural, or commercial decisions without authorized sign-off."
    )
    run_sub.font.size = Pt(9)
    run_sub.font.italic = True
    run_sub.font.color.rgb = RGBColor(133, 100, 4)

    doc.add_paragraph()  # Spacer

    # 2. Document Title and Metadata Header
    title_p = doc.add_paragraph()
    title_run = title_p.add_run("{{title}}")
    title_run.font.size = Pt(20)
    title_run.font.bold = True
    title_run.font.color.rgb = RGBColor(15, 23, 42)

    meta_table = doc.add_table(rows=3, cols=2)
    meta_table.alignment = WD_TABLE_ALIGNMENT.CENTER
    meta_table.autofit = False

    labels = [
        ("Document ID:", "{{doc_id}}", "Date:", "{{date}}"),
        ("Run ID:", "{{run_id}}", "Prepared By:", "{{prepared_by}}"),
        ("Clearance Level:", "{{clearance}}", "Classification:", "CONFIDENTIAL / PROPRIETARY"),
    ]

    for row_idx, (l1, v1, l2, v2) in enumerate(labels):
        row = meta_table.rows[row_idx]
        row.cells[0].paragraphs[0].add_run(f"{l1} ").bold = True
        row.cells[0].paragraphs[0].add_run(v1)
        row.cells[1].paragraphs[0].add_run(f"{l2} ").bold = True
        row.cells[1].paragraphs[0].add_run(v2)

    doc.add_paragraph()

    # 3. Equipment / Asset Information
    h2 = doc.add_heading("1. Equipment & Inspection Metadata", level=1)
    asset_p = doc.add_paragraph()
    asset_p.add_run("Target Asset Identifier: ").bold = True
    asset_p.add_run("{{asset_id}}\n")
    asset_p.add_run("Asset Description: ").bold = True
    asset_p.add_run("{{asset_name}}\n")
    asset_p.add_run("Inspection Date: ").bold = True
    asset_p.add_run("{{inspection_date}}\n")
    asset_p.add_run("Lead Field Inspector: ").bold = True
    asset_p.add_run("{{inspector}}")

    # 4. Findings (Facts) — Each with Source Reference
    doc.add_heading("2. Verified Field Findings (Facts)", level=1)
    p_fact_desc = doc.add_paragraph(
        "The following findings represent verified facts extracted from source inspection documentation. "
        "Every factual claim cites its exact file name and page reference."
    )
    p_fact_desc.runs[0].font.italic = True
    doc.add_paragraph("{{findings}}")

    # 5. Visual Observations (Observed vs Inferred)
    doc.add_heading("3. Visual Observations (Multimodal Findings)", level=1)
    p_vis_desc = doc.add_paragraph(
        "Visual observations derived from photographic evidence and non-destructive examination imaging. "
        "Labeled as Observed or Inferred per engineering boundary protocol."
    )
    p_vis_desc.runs[0].font.italic = True
    doc.add_paragraph("{{visual_observations}}")

    # 6. Applicable Internal Guidance (SOP References)
    doc.add_heading("4. Applicable Standard Operating Procedures (SOP)", level=1)
    doc.add_paragraph("{{sop_references}}")

    # 7. Engineering Calculations & Numerical Assessments
    doc.add_heading("5. Engineering Calculations & Assessments", level=1)
    doc.add_paragraph(
        "Deterministic computations evaluated via verified safe calculation engine:\n{{calculations}}"
    )

    # 8. Recommendations (Separated from Facts)
    doc.add_heading("6. Engineering Recommendations", level=1)
    p_rec_desc = doc.add_paragraph(
        "Recommendations are clearly distinguished from factual observations and are derived from "
        "applicable internal SOP guidance."
    )
    p_rec_desc.runs[0].font.italic = True
    doc.add_paragraph("{{recommendations}}")

    # 9. Requested Actions
    doc.add_heading("7. Requested Corrective Actions", level=1)
    doc.add_paragraph("{{actions}}")

    # 10. Human Review Gate (MANDATORY BLANK SECTION)
    doc.add_heading("8. Formal Human Review & Sign-Off Gate", level=1)
    doc.add_paragraph(
        "Mandatory Sign-Off: An authorized reviewer must review this draft deliverable. "
        "The AI workbench agent is strictly prohibited from approving its own work."
    )

    review_table = doc.add_table(rows=5, cols=2)
    review_table.alignment = WD_TABLE_ALIGNMENT.CENTER
    review_labels = [
        ("Designated Reviewer:", "________________________________________"),
        ("Review Decision:", "[   ] APPROVED    [   ] REJECTED    [   ] CHANGES REQUESTED"),
        ("Reviewer Comments:", "\n\n____________________________________________________"),
        ("Authorized Signature:", "________________________________________"),
        ("Date of Review:", "____________________"),
    ]
    for r_idx, (lab, val) in enumerate(review_labels):
        row = review_table.rows[r_idx]
        cell_l = row.cells[0]
        cell_r = row.cells[1]
        set_cell_background(cell_l, "F8FAFC")
        cell_l.paragraphs[0].add_run(lab).bold = True
        cell_r.paragraphs[0].add_run(val)

    # 11. Disclaimer Footer
    doc.add_paragraph()
    disc_p = doc.add_paragraph()
    disc_p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    disc_run = disc_p.add_run(
        "--- END OF APPROVAL NOTE DRAFT ---\n"
        "Confidential property of Sovereign AI Workbench. Local air-gapped generation."
    )
    disc_run.font.size = Pt(8.5)
    disc_run.font.italic = True
    disc_run.font.color.rgb = RGBColor(100, 116, 139)

    doc.save(str(output_path))
    print(f"Created: {output_path}")


def make_report_template(output_path: Path):
    """Create general engineering report template."""
    doc = docx.Document()

    # Title
    title_p = doc.add_paragraph()
    run = title_p.add_run("{{title}}")
    run.font.size = Pt(22)
    run.font.bold = True
    run.font.color.rgb = RGBColor(15, 23, 42)

    # Metadata
    meta = doc.add_paragraph()
    meta.add_run("Document ID: ").bold = True
    meta.add_run("{{doc_id}}  |  ")
    meta.add_run("Date: ").bold = True
    meta.add_run("{{date}}  |  ")
    meta.add_run("Author: ").bold = True
    meta.add_run("{{author}}\n")

    doc.add_heading("Executive Summary", level=1)
    doc.add_paragraph("{{summary}}")

    doc.add_heading("Technical Assessment", level=1)
    doc.add_paragraph("{{content}}")

    doc.add_heading("References & Citations", level=1)
    doc.add_paragraph("{{sources}}")

    doc.save(str(output_path))
    print(f"Created: {output_path}")


def make_presentation_template(output_path: Path):
    """Create professional slide presentation template."""
    prs = pptx.Presentation()

    # Slide 1: Title Slide (layout 0)
    title_slide_layout = prs.slide_layouts[0]
    slide = prs.slides.add_slide(title_slide_layout)
    title = slide.shapes.title
    subtitle = slide.placeholders[1]
    title.text = "{{title}}"
    subtitle.text = "{{subtitle}}\nAuthor: {{author}} | Date: {{date}}"

    # Slide 2: Agenda Slide (layout 1)
    bullet_slide_layout = prs.slide_layouts[1]
    slide2 = prs.slides.add_slide(bullet_slide_layout)
    shapes2 = slide2.shapes
    shapes2.title.text = "Agenda & Overview"
    tf2 = shapes2.placeholders[1].text_frame
    tf2.text = "{{agenda}}"

    # Slide 3: Content Slide (layout 1)
    slide3 = prs.slides.add_slide(bullet_slide_layout)
    shapes3 = slide3.shapes
    shapes3.title.text = "{{content_title}}"
    tf3 = shapes3.placeholders[1].text_frame
    tf3.text = "{{content_bullets}}"

    # Slide 4: Sources & Evidence (layout 1)
    slide4 = prs.slides.add_slide(bullet_slide_layout)
    shapes4 = slide4.shapes
    shapes4.title.text = "Sources & Traceability"
    tf4 = shapes4.placeholders[1].text_frame
    tf4.text = "{{sources}}"

    prs.save(str(output_path))
    print(f"Created: {output_path}")


if __name__ == "__main__":
    templates_dir = Path("templates")
    templates_dir.mkdir(parents=True, exist_ok=True)

    make_approval_note_template(templates_dir / "approval_note.docx")
    make_report_template(templates_dir / "report.docx")
    make_presentation_template(templates_dir / "presentation.pptx")
