"""Agent state definition and structured sub-models for Sovereign AI Workbench.

Implements the LangGraph state contract specified in 02_DESIGN_DOC.md section 6.2:
FileRef, ContentRef, VisualObservation, ChunkRef, PlanStep, ToolResult,
ArtifactRef, ValidationResult, AuditEventRef, and AgentState.
"""

from typing import Any, Dict, List, Literal, Optional, TypedDict
from pydantic import BaseModel, Field


class FileRef(BaseModel):
    """Reference to an uploaded or internal source file."""

    id: str
    path: str
    modality: str  # text, pdf, image, scanned_pdf, tabular
    pages: Optional[int] = None


class ContentRef(BaseModel):
    """Reference to parsed content (OCR / extracted text) stored on disk."""

    file_id: str
    page: Optional[int] = None
    storage_path: str
    content_type: str = "text"


class VisualObservation(BaseModel):
    """Structured visual observation from vision model (Gemma 4 E4B).

    Per 02_DESIGN_DOC.md §9.3, limitation is mandatory. Never called a measurement.
    """

    component: str
    visible_condition: str
    source: str  # e.g. "page_7_image_1"
    limitation: str  # Mandatory limitation notice
    type: Literal["observed", "inferred"] = "observed"
    confidence: Literal["low", "medium", "high"] = "medium"


class ChunkRef(BaseModel):
    """Reference to a retrieved knowledge base chunk with provenance."""

    chunk_id: str
    doc_id: str
    filename: str
    page: Optional[int] = None
    section: Optional[str] = None
    doc_version: Optional[str] = None
    classification: str = "INTERNAL"
    snippet: Optional[str] = None


class PlanStep(BaseModel):
    """An individual execution step produced by the planner."""

    step_id: int
    tool: str
    args: Dict[str, Any] = Field(default_factory=dict)
    reason: Optional[str] = None


class ToolResult(BaseModel):
    """Outcome of a single tool execution."""

    step_id: int
    tool: str
    status: Literal["ok", "error"]
    output: Optional[Dict[str, Any]] = None
    duration_ms: Optional[int] = None
    error: Optional[str] = None


class ArtifactRef(BaseModel):
    """Reference to a deliverable artifact generated by the run."""

    id: str
    kind: str  # docx, xlsx, pptx, code
    filename: str
    path: str
    sha256: str


class ValidationResult(BaseModel):
    """Validation rule result verifying output integrity."""

    rule: str
    passed: bool
    detail: Optional[str] = None


class AuditEventRef(BaseModel):
    """Summary reference to an audit event emitted during the run."""

    seq: int
    event_type: str
    status: str
    timestamp: str


class AgentState(TypedDict, total=False):
    """Central mutable state passed across LangGraph nodes."""

    run_id: str
    user_id: str
    user_role: str
    user_clearance: str  # PUBLIC | INTERNAL | CONFIDENTIAL | RESTRICTED
    user_request: str
    task_type: str
    complexity: str
    risk: str
    selected_model: str  # e.g. "qwen3.5:4b"
    route_reason: str
    uploaded_files: List[FileRef]
    parsed_content: Dict[str, ContentRef]
    visual_observations: List[VisualObservation]
    retrieved_chunks: List[ChunkRef]
    plan: List[PlanStep]
    tool_results: List[ToolResult]
    generated_artifacts: List[ArtifactRef]
    validation_results: List[ValidationResult]
    approval_status: str  # NONE | PENDING_REVIEW | APPROVED | REJECTED
    retry_count: int
    step_count: int
    audit_events: List[AuditEventRef]
    errors: List[str]
    final_answer: Optional[str]
